# Роль, которая может запускать команды раздачи
giveaway_role: "Giveaway"


# ПРОДОЛЖЕНИЕ, DND, ОНЛАЙН, ОФФЛАЙН
bot_activity: idle

# Сколько секунд до отмены настройки из-за отсутствия отправки информации
setup_timeout: 15.0

# Смайлик, на который пользователь должен реагировать, чтобы принять участие в розыгрыше - Unicode.

react_emoji: "🎉"

# Верно / Неверно - отправляет сообщение с пингом, уведомляющее победителя о том, что он выиграл.

ping_winner_message: True
